#PBS -P QCL_KF
#PBS -N AKF_GPR_finalfigs_correctQ
#PBS -J 1-16
#PBS -M riddhi.sw@gmail.com
#PBS -m abe
#PBS -l select=1:ncpus=1:mem=80GB
#PBS -l walltime=200:00:00 
#PBS -q defaultQ
#PBS -j oe

cd $PBS_O_WORKDIR/

test_case=(0 15 23 24 24 24 24 22 21 21 22 27 27 27 19 19 19)
variation=(0 12 11 1 2 4 7 2 1 5 3 1 5 8 1 5 8)

module load python

python ./test_script_AKF_finalfigs.py ${test_case} ${variation[$PBS_ARRAY_INDEX]} /scratch/RDS-FSC-QCL_KF-RW/Kalman
