#PBS -P QCL_KF
#PBS -N job_3_test_case_6
#PBS -J 1-13
#PBS -M riddhi.sw@gmail.com
#PBS -m abe
#PBS -l select=1:ncpus=1:mem=20GB
#PBS -l walltime=24:00:00 
#PBS -q defaultQ
#PBS -j oe

cd $PBS_O_WORKDIR/

test_case=6
variation=(0 1 2 3 4 5 6 7 8 9 10 11 12 13)
var_n_train_=2000
var_n_predict_=50
var_multiplier_=(0 20.0 18.0 16.0 14.0 12.0 10.0 5.0 4.0 3.0 2.0 1.8 1.25 1.0)
var_f0_=0.000888888889
var_J_=123750
var_alpha_=1000.0
var_noiselvl_=0.01

module load python

python ./test_script_generator.py ${test_case} ${variation[$PBS_ARRAY_INDEX]} ${var_f0_} ${var_J_} ${var_multiplier_[$PBS_ARRAY_INDEX]} ${var_n_train_} ${var_n_predict_} ${var_alpha_} ${var_noiselvl_} /scratch/RDS-FSC-QCL_KF-RW/Kalman/test_case_${test_case}

