#PBS -P QCL_KF
#PBS -N job_3_test_case_17
#PBS -J 1-3
#PBS -M riddhi.sw@gmail.com
#PBS -m abe
#PBS -l select=1:ncpus=1:mem=80GB
#PBS -l walltime=200:00:00 
#PBS -q defaultQ
#PBS -j oe

cd $PBS_O_WORKDIR/

# Test_case 17 == takes variant 5 from test_case_16 and tests for different fourier resolution by increasing n_train, and by setting alpha=1000.0, n_predict =100

test_case=17
variation=(0 1 2 3)
var_n_train_=(0, 2000, 4000, 8000)
var_n_predict_=100
var_multiplier_=20
var_f0_=0.0008888889
var_J_=45000
var_alpha_=1000.0
var_noiselvl_=0.01

module load python

python ./test_script_generator_whitenoise.py ${test_case} ${variation[$PBS_ARRAY_INDEX]} ${var_f0_} ${var_J_} ${var_multiplier_} ${var_n_train_[$PBS_ARRAY_INDEX]} ${var_n_predict_} ${var_alpha_} ${var_noiselvl_} /scratch/RDS-FSC-QCL_KF-RW/Kalman/test_case_${test_case}
