#PBS -P QCL_KF
#PBS -N job_3_test_case_23
#PBS -J 1-13
#PBS -M riddhi.sw@gmail.com
#PBS -m abe
#PBS -l select=1:ncpus=1:mem=100GB
#PBS -l walltime=400:00:00 
#PBS -q defaultQ
#PBS -j oe

cd $PBS_O_WORKDIR/
# Test_case_23 attempts to narrowly examine the change
# from Variation 12 Test Case 15 to variation 11 Test Case 15.

test_case=23
variation=(0 1 2 3 4 5 6 7 8 9 10 11 12 13)
var_n_train_=2000
var_n_predict_=50
var_multiplier_=20
var_f0_=(0 0.25 0.3 0.35 0.4 0.45 0.48 0.49 0.493 0.495 0.497 0.499 0.49999 0.5)
var_J_=(0 160 133 114 100 89 83 82 81 81 80 80 80 80)
var_alpha_=1.0
var_noiselvl_=0.01

module load python

python ./test_script_generator_whitenoise.py ${test_case} ${variation[$PBS_ARRAY_INDEX]} ${var_f0_[$PBS_ARRAY_INDEX]} ${var_J_[$PBS_ARRAY_INDEX]} ${var_multiplier_} ${var_n_train_} ${var_n_predict_} ${var_alpha_} ${var_noiselvl_} /scratch/RDS-FSC-QCL_KF-RW/Kalman/test_case_${test_case}




