#PBS -P QCL_KF
#PBS -N plotter_1
#PBS -M riddhi.sw@gmail.com
#PBS -m abe
#PBS -l select=1:ncpus=1:mem=80GB
#PBS -l walltime=10:00:00 
#PBS -q defaultQ
#PBS -j oe

cd $PBS_O_WORKDIR/
# Plotting job where kf.fast_2 needs to be implemented and there is a memory
# error if run on cluster directly.

source env/bin/activate
export MPLBACKEND=Agg
echo $MPLBACKEND
which python

python KF_pred_comparison.py
python KF_loss_comparison.py
