#PBS -P QCL_KF
#PBS -N RGtestjobarray
#PBS –J 0-2
#PBS -M riddhi.sw@gmail.com
#PBS -m abe # a = aborts, b = begins, e = ends
#PBS -l select=1:ncpus=1:mem=8GB
#PBS -l walltime=00:10:00 
#PBS -q defaultQ
#PBS -j oe # one log file

cd $PBS_O_WORKDIR/
#source ./env/bin/activate

test_case=(1 2 3)
variation=(0 0 0)
var_f0_=(2.0 2.0 1.33333333333333333)
var_J_=(3 20 30)

cd /scratch/RDS-FSC-QCL_KF-RW/Kalman/test_case_${test_case[$PBS_ARRAY_INDEX]}

module load python

python test_script_generator.py ${test_case[$PBS_ARRAY_INDEX]} ${variation[$PBS_ARRAY_INDEX]} ${var_f0_[$PBS_ARRAY_INDEX]} ${var_J_[$PBS_ARRAY_INDEX]} /scratch/RDS-FSC-QCL_KF-RW/Kalman/test_case_${test_case[$PBS_ARRAY_INDEX]}

#deactivate
