'''
    Package: data_tools
    Language: Python 2.7

    Modules:
    -------
        common : List of functions required by multiple modules in data_tools.
        load_raw_cluster_data : Load data and analyse data generated by any algorithm
            (LKFFB, AKF, LSF, GPR).
        data_risk_analysis : Implements Bayes Risk analysis for all algorithms.
        data_tuned_run_analysis : Generates single predictions and spectrum estimates
            from tuned algorithms.

    Author: Riddhi Gupta <riddhi.sw@gmail.com>
'''
