#PBS -P QCL_KF
#PBS -N job_2_test_case_27
#PBS -J 1-8
#PBS -M riddhi.sw@gmail.com
#PBS -m abe
#PBS -l select=1:ncpus=1:mem=20GB
#PBS -l walltime=24:00:00 
#PBS -q defaultQ
#PBS -j oe

cd $PBS_O_WORKDIR/

test_case=27
variation=(0 1 2 3 4 5 6 7 8)
var_n_train_=2000
var_n_predict_=100
var_multiplier_=20
var_f0_=0.5
var_J_=80
var_alpha_=1.0
var_noiselvl_=(0 0.01 0.025 0.05 0.075 0.1 0.15 0.2 0.25)

module load python

python ./test_script_generator_whitenoise.py ${test_case} ${variation[$PBS_ARRAY_INDEX]} ${var_f0_} ${var_J_} ${var_multiplier_} ${var_n_train_} ${var_n_predict_} ${var_alpha_} ${var_noiselvl_[$PBS_ARRAY_INDEX]} /scratch/RDS-FSC-QCL_KF-RW/Kalman/test_case_${test_case}

