#PBS -P QCL_KF
#PBS -N job_3_test_case_15
#PBS -J 1-13
#PBS -M riddhi.sw@gmail.com
#PBS -m abe
#PBS -l select=1:ncpus=1:mem=80GB
#PBS -l walltime=200:00:00 
#PBS -q defaultQ
#PBS -j oe

cd $PBS_O_WORKDIR/

# Ends at test_case_14 (== test_case_7 for white noise).
# Starts at undersampling with perfect projection
# Variation three is closest version of test_case_10 and test_case_11 (undersampling with imperfect learning, under white noise, and easy f0 respectively)

test_case=15
variation=(0 1 2 3 4 5 6 7 8 9 10 11 12 13)
var_n_train_=2000
var_n_predict_=50
var_multiplier_=20
var_f0_=(0 0.000625 0.00078125 0.001 0.00125 0.0015625 0.0025 0.003125 0.00625 0.025 0.0625 0.25 0.5 1)
var_J_=(0 64000 51200 40000 32000 25600 16000 12800 6400 1600 640 160 80 40)
var_alpha_=1.0
var_noiselvl_=0.01

module load python

python ./test_script_generator_whitenoise.py ${test_case} ${variation[$PBS_ARRAY_INDEX]} ${var_f0_[$PBS_ARRAY_INDEX]} ${var_J_[$PBS_ARRAY_INDEX]} ${var_multiplier_} ${var_n_train_} ${var_n_predict_} ${var_alpha_} ${var_noiselvl_} /scratch/RDS-FSC-QCL_KF-RW/Kalman/test_case_${test_case}





